# Generated by Django 3.2.14 on 2022-07-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0015_auto_20220307_1522"),
        ("notifications_api_common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsconfig",
            name="notifications_api_service",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"api_type": "nrc"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="zgw_consumers.service",
                verbose_name="notifications api service",
            ),
        ),
    ]
