# Generated by Django 5.2.3 on 2025-06-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api_common', '0009_add_subscription_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsconfig',
            name='notification_delivery_base_factor',
            field=models.PositiveIntegerField(default=2, help_text='The base factor used for exponential backoff. Default is 2 (binary), but can be increased (e.g., 3 or 4) to spread retries over a longer time period.'),
        ),
    ]
