# Generated by Django 5.2.3 on 2025-07-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api_common', '0009_add_subscription_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsconfig',
            name='notification_delivery_base_factor',
            field=models.PositiveIntegerField(default=4, help_text='The base factor used for exponential backoff. This can be increased or decreased to spread retries over a longer or shorter time period.'),
        ),
        migrations.AlterField(
            model_name='notificationsconfig',
            name='notification_delivery_max_retries',
            field=models.PositiveIntegerField(default=7, help_text='The maximum number of automatic retries. After this amount of retries, guaranteed delivery stops trying to deliver the message.'),
        ),
        migrations.AlterField(
            model_name='notificationsconfig',
            name='notification_delivery_retry_backoff',
            field=models.PositiveIntegerField(default=25, help_text='If specified, a factor applied to the exponential backoff. This allows you to tune how quickly automatic retries are performed.'),
        ),
        migrations.AlterField(
            model_name='notificationsconfig',
            name='notification_delivery_retry_backoff_max',
            field=models.PositiveIntegerField(default=52000, help_text='An upper limit in seconds to the exponential backoff time.'),
        ),
    ]
