# Generated by Django 5.2.7 on 2026-06-01 17:47

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api_common', '0010_notificationsconfig_notification_delivery_base_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('type', models.CharField(choices=[('notification', 'Notification'), ('cloudevent', 'Cloudevent')], default='demnotificationo')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1, help_text='Indicates to which delivery attempt this response belongs.', verbose_name='attempt')),
                ('exception', models.CharField(blank=True, max_length=1000)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('failed_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications_api_common.notification')),
            ],
        ),
    ]
